spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      sql-dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: ADIL LAHIB's Orders System
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    username: #########
    password: #########
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true

flyway:
  baseline-on-migrate: true

server:
  port: 8181
##logging:
##  level:
##    org:
##      springframework : debug





